file:
    upload:
        extension: .ser
        folder:
            channel:
                name: channels
            message:
                name: messages
            user:
                name: users
            file:
                name: files
            userStatus:
                name: userStatus
            readStatus:
                name: readStatus
            binaryContent:
                name: binaryContents
        path: C:\\spring\\codeit-bootcamp-spring\\6-sprint-mission\\src\\main\\resources\\data\\
spring:
    application:
        name: discodeit

code:
  repository:
          type: file


server:
  port: 8080





